---
title: "Consumer Complaint Data"
author: "Diana Rodriguez"
date: "5/8/2022"
output: html_document
flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(writexl)
library(viridis)
library(dplyr)

library(tigris)
library(sf)
library(tmap)
library(tmaptools)
library(htmltools)
library(janitor)
library(rmapshaper)
library(here)
library(flexdashboard)
library(DT)
options(tigris_class = "sf")
```

```{r}

complaints_raw <- read_rds("data/complaints.rds")

complaints <- complaints_raw %>% 
  clean_names()

head(complaints)

```

```{r}

complaints %>% 
  filter(state == "CA") %>% 
  count(issue,sort = TRUE) %>% 
  arrange(desc(issue))

```

# Top Company Complaints in California

```{r}

CA <- complaints %>% 
  filter(state == "CA")

CA_companies <- CA %>%
  group_by(company, issue) %>% 
  count(issue, sort = TRUE)

Top_CA_companies <- head(CA_companies,5)

ggplot(Top_CA_companies, aes(x = reorder(company,issue), y = n))+
  geom_col(color = "#FD8F6B", fill = "#FD8F6B")+
  theme(axis.text.x.left = element_text(size = .05))+
  coord_flip()+
  scale_y_continuous(name = "amount of complaints", labels = scales::comma) +
  scale_x_discrete(name = "companies") +
  labs(title = "California Company Complaints",
  subtitle = "2020") + 
  theme_minimal()



```
# Most Common Categories of Complaints 

```{r}

CA_complaints <- CA %>%
  group_by(issue) %>% 
  count(issue, sort = TRUE)

Top_complaints <- 
  head(CA_complaints,5)

ggplot(Top_complaints, aes(x = reorder(issue,n), y = n))+
  geom_col(color = "#46A5E5", fill = "#46A5E5")+
  theme(axis.text.x.left = element_text(size = 5))+
  coord_flip()+
  scale_y_continuous(name = "Number of Complaints ", labels = scales::comma) +
  scale_x_discrete(name = "Kinds of Complaints") +
  labs(title = "California Common Complaints",
  subtitle = "2020") + 
  theme_minimal()


```

# Mentions of COVID in Consumer Complaints 

```{r}







```




